#[doc = "Register `ROOT_PORT_REQUESTOR_ID` reader"]
pub type R = crate::R<RootPortRequestorIdSpec>;
#[doc = "Register `ROOT_PORT_REQUESTOR_ID` writer"]
pub type W = crate::W<RootPortRequestorIdSpec>;
#[doc = "Field `RPRI` reader - Root Port Requestor ID \\[RPRI\\]
RID (bus, device and function numbers) for all TLPs internally generated by Root Port"]
pub type RpriR = crate::FieldReader<u16>;
#[doc = "Field `RPRI` writer - Root Port Requestor ID \\[RPRI\\]
RID (bus, device and function numbers) for all TLPs internally generated by Root Port"]
pub type RpriW<'a, REG> = crate::FieldWriter<'a, REG, 16, u16>;
#[doc = "Field `R0` reader - Reserved \\[R0\\]
Reserved"]
pub type R0R = crate::FieldReader<u16>;
impl R {
    #[doc = "Bits 0:15 - Root Port Requestor ID \\[RPRI\\]
RID (bus, device and function numbers) for all TLPs internally generated by Root Port"]
    #[inline(always)]
    pub fn rpri(&self) -> RpriR {
        RpriR::new((self.bits & 0xffff) as u16)
    }
    #[doc = "Bits 16:31 - Reserved \\[R0\\]
Reserved"]
    #[inline(always)]
    pub fn r0(&self) -> R0R {
        R0R::new(((self.bits >> 16) & 0xffff) as u16)
    }
}
impl W {
    #[doc = "Bits 0:15 - Root Port Requestor ID \\[RPRI\\]
RID (bus, device and function numbers) for all TLPs internally generated by Root Port"]
    #[inline(always)]
    #[must_use]
    pub fn rpri(&mut self) -> RpriW<RootPortRequestorIdSpec> {
        RpriW::new(self, 0)
    }
}
#[doc = "Root Port Requestor ID Register Reserved\n\nYou can [`read`](crate::generic::Reg::read) this register and get [`root_port_requestor_id::R`](R).  You can [`reset`](crate::generic::Reg::reset), [`write`](crate::generic::Reg::write), [`write_with_zero`](crate::generic::Reg::write_with_zero) this register using [`root_port_requestor_id::W`](W). You can also [`modify`](crate::generic::Reg::modify) this register. See [API](https://docs.rs/svd2rust/#read--modify--write-api)."]
pub struct RootPortRequestorIdSpec;
impl crate::RegisterSpec for RootPortRequestorIdSpec {
    type Ux = u32;
}
#[doc = "`read()` method returns [`root_port_requestor_id::R`](R) reader structure"]
impl crate::Readable for RootPortRequestorIdSpec {}
#[doc = "`write(|w| ..)` method takes [`root_port_requestor_id::W`](W) writer structure"]
impl crate::Writable for RootPortRequestorIdSpec {
    type Safety = crate::Unsafe;
    const ZERO_TO_MODIFY_FIELDS_BITMAP: u32 = 0;
    const ONE_TO_MODIFY_FIELDS_BITMAP: u32 = 0;
}
#[doc = "`reset()` method sets ROOT_PORT_REQUESTOR_ID to value 0"]
impl crate::Resettable for RootPortRequestorIdSpec {
    const RESET_VALUE: u32 = 0;
}
